services:
  api:
    build: .
    container_name: sneakers_api
    working_dir: /app
    depends_on:
      - db
      - redis
    expose:
      - "8000"
    volumes:
      - ~/data/solesearch:/var/data/solesearch
    networks:
      - sneakers_network
    restart: always
    env_file:
      - ".env"

  celery_worker:
    build: .
    container_name: sneakers_worker
    working_dir: /app
    command: celery -A solesearch_api.tasks worker --loglevel=info
    depends_on:
      - api
      - redis
      - rabbitmq
    volumes:
      - ~/data/solesearch:/var/data/solesearch
    networks:
      - sneakers_network
    restart: always
    env_file:
      - ".env"

  celery_beat:
    build: .
    container_name: sneakers_beat
    command: celery -A solesearch_api.tasks beat --loglevel=info
    depends_on:
      - api
      - redis
      - rabbitmq
    volumes:
      - ~/data/solesearch:/var/data/solesearch
    networks:
      - sneakers_network
    restart: always
    env_file:
      - ".env"

  nginx:
    image: nginx:alpine-slim
    container_name: sneakers_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.local.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
    networks:
      - sneakers_network
    restart: always

  db:
    image: postgres:16-alpine
    container_name: sneakers_db
    environment:
      POSTGRES_DB: Sneakers
      POSTGRES_USER: solesearch
      POSTGRES_PASSWORD: solesearch
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - sneakers_network
    restart: always

  redis:
    image: redis:alpine
    container_name: sneakers_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - sneakers_network
    restart: always

  rabbitmq:
    image: rabbitmq:alpine
    container_name: sneakers_rabbitmq
    ports:
      - "5672:5672"
    networks:
      - sneakers_network
    environment:
      - RABBITMQ_DEFAULT_USER=solesearch
      - RABBITMQ_DEFAULT_PASS=solesearch
    restart: always

volumes:
  postgres_data:
  redis_data:


networks:
  sneakers_network:
    driver: bridge
