[project]
name = "api"
version = "0.0.1"
authors = [
  { name="Peter Rauscher", email="peter@peterrauscher.com" },
]
description = "API package for SoleSearch"
requires-python = ">=3.12"
dependencies = [
  "fastapi",
  "motor",
  "python-dotenv",
  "uvicorn",
  "pydantic",
  "mangum",
  "core @ git+ssh://git@github.com/SoleSearch-Demos/core.git@main",
]

[project.urls]
Homepage = "https://github.com/SoleSearch-Demos/api"
Issues = "https://github.com/SoleSearch-Demos/api/issues"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/api"]

[tool.hatch.build.targets.sdist]
packages = ["src/api"]
require-runtime-dependencies = true

[tool.hatch.build.targets.sdist.force-include]
".env" = "/.env"
"envs/lambda/Lib/site-packages" = "/"

[tool.hatch.envs.lambda]
path = "envs/lambda"

[tool.hatch.envs.dev]
pre-install-commands = ["pip install -e ../core"]
scripts.start = "uvicorn src.api.main:app --reload"