[build-system]
requires = ["hatchling", "hatch-zipped-directory"]
build-backend = "hatchling.build"

[project]
name = "api"
dynamic = ["version"]
authors = [
  { name="Peter Rauscher", email="peter@peterrauscher.com" },
]
description = "API package for SoleSearch"
requires-python = ">=3.12"
dependencies = [
  "fastapi",
  "motor",
  "python-dotenv",
  "uvicorn",
  "pydantic",
  "mangum",
  "Authlib",
  "httpx",
  "Starlette",
  "itsdangerous",
  "core @ git+ssh://git@github.com/SoleSearch-Demos/core.git@main",
]

[tool.hatch.version]
path = "src/api/__about__.py"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.envs.default.scripts]
start = "python -m api.server"

[tool.hatch.envs.dev]
pre-install-commands = ["pip install -e ../core"]
scripts.start = "uvicorn src.api.main:app --reload"

[tool.hatch.build.targets.wheel]
packages = ["src/api"]

[tool.hatch.build.targets.sdist]
packages = ["src/api"]

[tool.hatch.build.targets.zipped-directory]
install-name = ""
sources = ["src/api"]

[tool.hatch.build.targets.zipped-directory.force-include]
".env" = "/.env"