[tool.poetry]
name = "api"
version = "2.0.0"
description = ""
authors = ["Peter Rauscher"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "*"
python-dotenv = "*"
uvicorn = "*"
mangum = "*"
requests = "*"
Starlette = "*"
itsdangerous = "*"
core = { git = "ssh://git@github.com/SoleSearch-Demos/core.git", branch = "main" }
celery = { extras = ["redis"], version = "^5.4.0" }
sqlmodel = "^0.0.21"

[tool.poetry.group.dev.dependencies]
ruff = "*"
black = "*"
pre-commit = "^3.8.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
select = [
    "E",   # pycodestyle error
    "W",   # pycodestyle warning
    "F",   # pyflakes
    "A",   # flakes8-builtins
    "COM", # flakes8-commas
    "C4",  # flake8-comprehensions
    "Q",   # flake8-quotes
    "SIM", # flake8-simplify
    "PTH", # flake8-use-pathlib
    "I",   # isort
    "N",   # pep8 naming
    "UP",  # pyupgrade  
    "S",   # bandit
]
