[project]
name = "api"
version = "0.0.1"
authors = [
  { name="Peter Rauscher", email="peter@peterrauscher.com" },
]
description = "API package for SoleSearch"
requires-python = ">=3.12"
dependencies = [
  "fastapi",
  "motor",
  "python-dotenv",
  "uvicorn",
  "pydantic",
  "core @ git+ssh://git@github.com/SoleSearch-Demos/core.git@main",
]

[project.urls]
Homepage = "https://github.com/SoleSearch-Demos/api"
Issues = "https://github.com/SoleSearch-Demos/api/issues"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/api"]

[tool.hatch.envs.dev]
pre-install-commands = ["pip install -e ../core"]