name: Build Deployment Image
on:
  push:
    tags:
      - "*"

permissions:
  contents: write
  packages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.1"

      - name: Install dependencies
        run: |
          python -m pip install --user pipx
          python -m pipx ensurepath
          pipx install hatch

      - name: Create .env file
        run: |
          echo "${{ secrets.SOLESEARCH_ENV_FILE }}" > .env
        shell: bash

      - name: Build zip
        run: |
          hatch build -t zipped-directory
          dist_dir="dist/"
          zip_file=$(find "$dist_dir" -type f -name "*.zip" -print -quit)
          build_file=$(realpath "$zip_file")
          echo "Zip file found: $build_file"
          HATCH_SITE_PACKAGES_DIR=$(hatch env find)/lib/python3.12/site-packages
          cd $HATCH_SITE_PACKAGES_DIR
          zip -r $build_file *
        shell: bash

      - name: Publish to Github
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/*.zip
